<a href="https://colab.research.google.com/github/schmitfe/Nawrot_CNS_Course/blob/main/PythonProgramming_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# NumPy - Solutions

NumPy (Numerical Python) is a core Python library for numerical computation. It provides multidimensional arrays together with a rich collection of functions for applying mathematical operations to those arrays.


### Numpy Arrays

Numpy arrays are great alternatives to Python Lists. Specifically for scientific computing and numerical calculation numpy arrays are much easier to handle and do computation.

How to create a numpy array:

In [ ]:
# first we import numpy. Note that as we gonna call numpy again and again
# it is convenient to give a short name to like np
import numpy as np

arr1d = np.array([1,2,3]) # Create a one dimensional array
arr2d = np.array([[1,2,3],
               [4,5,6]]) # Create two dimensional array

print(arr1d.shape)
print(arr2d.shape)


Numpy also provides many functions to create arrays:

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

### Array indexing

To access any element(s) in numpy array we use index, something similar to Python lists with a difference that for each dimension of array we will have one index. For example extracting the second value of the first dimension of the arr2d would be: `arr2d[0,2]`.

Example:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 3  7  3  4]
#  [ 5  6  7  2]
#  [ 2  1  1  1]]
a = np.array([[3,7,3,4], [5,6,7,2], [2,1,1,1]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):

b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "7"
b[0, 0] = 3     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "3"

There are many useful functions in NumPy. Here we mention some of them.


where, add, random, reshape, vstack, mean, median, std, isnan,

**Exercises:**

1- Create a 3×3 numpy array of all True’s

# Solution

In [ ]:
true_array = np.ones((3, 3), dtype=bool)
print(true_array)


2- Extract all odd numbers from arr

hint: input: [0,1,2,3,4,5,6,7] and desired output: [1,3,5,7]

# Solution

In [ ]:
arr = np.arange(8)
print(arr[arr % 2 == 1])


3- Convert a 1D array to a 2D array with 2 rows

hint: input: [0,1,2,3,4,5,6,7], desired output: array([[0,1,2,3], [4,5,6,7]])

# Solution

In [ ]:
arr = np.arange(8)
print(arr.reshape(2, -1))


4- Stack arrays `a` and `b` vertically.
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

# Solution

In [ ]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.vstack((a, b)))


5- Get all items between 5 and 10 from a.

```
a = np.arange(0,15,2)
```

# Solution

In [ ]:
a = np.arange(0, 15, 2)
print(a[(a >= 5) & (a <= 10)])


6- find mean, median and standard deviation of a.

# Solution

In [ ]:
rng = np.random.default_rng(42)
a = rng.random(1000)
print('mean:', np.mean(a))
print('median:', np.median(a))
print('standard deviation:', np.std(a))


```
a = np.random.rand(1000)
```

# Matplotlib

Visualization is one of the most important parts of data analysis. It allows us to inspect large amounts of data quickly and communicate results clearly. In Python, one of the core plotting libraries is `matplotlib`.

`matplotlib.pyplot` offers a convenient stateful interface for making figures:
```
import matplotlib.pyplot as plt
```
In this course we will treat these as standard Python plotting commands and focus on reading, modifying, and writing clear plotting code.


In [ ]:
import matplotlib.pyplot as plt

# data to be plotted
X = [1,2,3,4]
Y = [10,22,30,40]

# plot
plt.plot(X, Y, '-o')
# define xlabel
plt.xlabel('X label')
# define ylabel
plt.ylabel('Y label')
# show the plotted figure
plt.show()

Check the following codes and the produced figures. Can you tell what each line of code is doing?

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# evenly sampled time at 200ms intervals
t = np.arange(0., 5., 0.2)

# red dashes, blue squares and green triangles
plt.plot(t, t, 'r', label='line one', linewidth=5)
plt.plot(t, t**2, 'b',label='line two', linewidth=2)
plt.plot(t,t**3, 'g^', label='marker', markersize = 4)
plt.legend()
plt.grid(True, color='k')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
population_age = [22,55,62,45,21,22,34,42,42,4,2,102,95,85,55,110,120,70,65,55,111,115,80,75,65,54,44,43,42,48]
bins = [0,10,20,30,40,50,60,70,80,90,100]
plt.hist(population_age, bins, histtype='bar', rwidth=0.8)
plt.xlabel('age groups')
plt.ylabel('Number of people')
plt.title('Histogram')
plt.show()

What you tried to do with the last two figures is the best way of learning matplotlib syntaxes and produces whatever figure that you like. Probably you did the following: Checking the firgure axes, colors, lines, labels, bars, etc and trying to figure out the line in the code responsible for that feature. This is a very efficient way to create figures and add whatever details you like. One of the best collections for these examples are the following link:

[https://matplotlib.org/gallery.html](https://matplotlib.org/gallery.html )

Click on the link and find the figure you are interested in and check the code for that figure.

As a good exercise try to find out how one can plot multiple subplots in one plot?


## Exercises

1. Plot two or more lines in one figure. Add a legend and use clearly different colors and line widths.
2. Plot two or more lines with different line styles.
3. Choose one figure from the matplotlib gallery and explain the script to your teammate.
4. Generate random values between 0 and 1000 and plot them. Use blue for values below 500 and red for values above 500.
5. Using the random values from exercise 4, create a new plot and add a marker wherever the value is above 800.
6. Using the random values from exercise 4, create a histogram in a new figure and choose a sensible bin size.
7. If you wrote a `time_resolved` function during the NumPy exercises, apply it to the data from exercise 4 and plot the result in a new figure. If not, first write a small helper function that computes a moving average or moving sum.
8. Combine the plots from exercises 4 to 7 into one figure using `plt.subplot` or `plt.subplots`.


## Solution

In [ ]:
rng = np.random.default_rng(42)
x = np.arange(200)
values = rng.uniform(0, 1000, size=x.size)
moving_average = np.convolve(values, np.ones(15) / 15, mode="valid")

fig, axes = plt.subplots(2, 2, figsize=(11, 8))

axes[0, 0].plot(x[values < 500], values[values < 500], "b.", label="< 500")
axes[0, 0].plot(x[values >= 500], values[values >= 500], "r.", label=">= 500")
axes[0, 0].legend()
axes[0, 0].set_title("Threshold colors")

axes[0, 1].plot(x, values, color="0.7")
axes[0, 1].plot(x[values > 800], values[values > 800], "k*", label="> 800")
axes[0, 1].legend()
axes[0, 1].set_title("Large values")

axes[1, 0].hist(values, bins=20)
axes[1, 0].set_title("Histogram")

axes[1, 1].plot(np.arange(len(moving_average)) + 7, moving_average)
axes[1, 1].set_title("15-sample moving average")

for ax in axes.flat:
    ax.set_xlabel("sample")
    ax.set_ylabel("value")
plt.tight_layout()
plt.show()
